export const initialFormValue = {
  email: "",
  name: "",
  age: "",
  education: "",
  institute: "",
  course: "",
  workExperience: "",
  canadianInstitute: "",
  programOfStudy: "",
  country: "",
  goals: "",
  listeningScores: "",
  readingScores: "",
  writingScores: "",
  speakingScores: "",
  tutionPaid: "",
  tutionFee: "",
  gicDone: "",
  gicFees: "",
};
